---
name: Tee
version: 0.13_51
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Pure Perl emulation of GNU tee
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  perl: 5.006
build_requires:
  Test::More: 0.47
provides:
  Tee:
    file: lib/Tee.pm
    version: 0.13_51
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
